import {
  DiscountClass,
  ProductDiscountSelectionStrategy,
  CartLinesDiscountsGenerateRunResult,
} from '../generated/api';

/**
 * Bundle configuration stored in the discount metafield
 */
interface AddOnConfig {
  addOnId: string;
  targetVariantIds: string[];
  discountType: 'PERCENTAGE' | 'FIXED_AMOUNT' | 'FIXED_PRICE' | 'FREE_GIFT';
  discountValue: number;
  subscriptionOnly: boolean;
  maxQuantity: number;
  message: string;
}

interface BundleConfig {
  bundleId: string;
  addOns: AddOnConfig[];
}

/**
 * Input types for the function (will be generated by typegen)
 */
interface CartLine {
  id: string;
  quantity: number;
  cost: {
    amountPerQuantity: {
      amount: string;
    };
  };
  merchandise: {
    __typename: string;
    id?: string;
    product?: {
      id: string;
    };
  };
  sellingPlanAllocation?: {
    sellingPlan: {
      id: string;
    };
  } | null;
}

interface CartInput {
  cart: {
    lines: CartLine[];
  };
  discount: {
    discountClasses: DiscountClass[];
    metafield?: {
      jsonValue: BundleConfig;
    } | null;
  };
}

export function cartLinesDiscountsGenerateRun(
  input: CartInput,
): CartLinesDiscountsGenerateRunResult {
  // Return early if no cart lines
  if (!input.cart.lines.length) {
    return { operations: [] };
  }

  // Check if we have product discount class
  const hasProductDiscountClass = input.discount.discountClasses.includes(
    DiscountClass.Product,
  );

  if (!hasProductDiscountClass) {
    return { operations: [] };
  }

  // Get bundle config from metafield
  const config = input.discount.metafield?.jsonValue;
  if (!config || !config.addOns || config.addOns.length === 0) {
    return { operations: [] };
  }

  // Build discount candidates for matching cart lines
  const candidates: Array<{
    message: string;
    targets: Array<{ cartLine: { id: string; quantity?: number } }>;
    value: { percentage?: { value: number }; fixedAmount?: { amount: string; appliesToEachItem: boolean } };
  }> = [];

  for (const addOn of config.addOns) {
    // Find cart lines that match this add-on's target variants
    for (const line of input.cart.lines) {
      // Only process ProductVariant merchandise
      if (line.merchandise.__typename !== 'ProductVariant') {
        continue;
      }

      const variantId = line.merchandise.id;
      if (!variantId || !addOn.targetVariantIds.includes(variantId)) {
        continue;
      }

      // Check subscription-only restriction
      if (addOn.subscriptionOnly && !line.sellingPlanAllocation) {
        continue;
      }

      // Calculate quantity to discount (respecting max quantity)
      const quantityToDiscount = Math.min(line.quantity, addOn.maxQuantity);

      // Calculate discount value based on type
      let discountValue: { percentage?: { value: number }; fixedAmount?: { amount: string; appliesToEachItem: boolean } };

      switch (addOn.discountType) {
        case 'PERCENTAGE':
          discountValue = {
            percentage: {
              value: addOn.discountValue,
            },
          };
          break;

        case 'FIXED_AMOUNT':
          discountValue = {
            fixedAmount: {
              amount: addOn.discountValue.toString(),
              appliesToEachItem: true,
            },
          };
          break;

        case 'FIXED_PRICE': {
          // Calculate discount as: original price - target price
          const originalPrice = parseFloat(line.cost.amountPerQuantity.amount);
          const targetPrice = addOn.discountValue;

          // Only apply if target price is less than original
          if (targetPrice >= originalPrice) {
            continue;
          }

          const discountAmount = originalPrice - targetPrice;
          discountValue = {
            fixedAmount: {
              amount: discountAmount.toFixed(2),
              appliesToEachItem: true,
            },
          };
          break;
        }

        case 'FREE_GIFT':
          // 100% off for free gifts
          discountValue = {
            percentage: {
              value: 100,
            },
          };
          break;

        default:
          continue;
      }

      candidates.push({
        message: addOn.message || `Add-On Discount`,
        targets: [
          {
            cartLine: {
              id: line.id,
              quantity: quantityToDiscount,
            },
          },
        ],
        value: discountValue,
      });
    }
  }

  // Return early if no discounts to apply
  if (candidates.length === 0) {
    return { operations: [] };
  }

  return {
    operations: [
      {
        productDiscountsAdd: {
          candidates,
          selectionStrategy: ProductDiscountSelectionStrategy.All,
        },
      },
    ],
  };
}
